Adding CUDA 11 jobs to Lassen CI
LLNL/RAJA pull request #1269
Opened 2022-05-24 22:15 UTC by kab163

# Summary

- This PR is simply updates the version of CUDA used in Lassen Gitlab CI jobs to CUDA 11 (both 11.0.2 and 11.5.0 jobs)

2022-05-24 22:26 UTC, davidbeckingsale commented
This looks good. You might find you need to load the cuda/11 module in the build script somewhere before running the tests.

2022-05-26 19:24 UTC, kab163 commented
> This looks good. You might find you need to load the cuda/11 module in the build script somewhere before running the tests.

It is looking like it isn't necessary to do that for the tests to pass, but should I try to do that stuff anyways for best practice?

2022-06-01 17:57 UTC, rhornung67 commented on .gitlab/lassen-jobs.yml
>  clang_9_cuda:
```suggestion
clang_9_cuda_11_0_2:
```

2022-06-01 17:59 UTC, rhornung67 commented on .gitlab/lassen-jobs.yml
> +    SPEC: "+openmp +cuda %xl@16.1.1.11 cxxflags='-qthreaded -std=c++14 -O3 -qstrict -qxlcompatmacros -qlanglvl=extended0x -qalias=noansi -qhot -qpic -qsmp=omp -qsuppress=1500-029 -qsuppress=1500-036'
The label should be cuda_11_0_2, not cuda_10 here

2022-06-01 17:59 UTC, rhornung67 requested changes
Please add full version info to all the labels so it is obvious what is being run when you look at the test pipelines.

2022-06-02 19:03 UTC, kab163 commented
Y'all can merge this when ready!

2022-06-02 20:57 UTC, merged