Artv3/caliper support
LLNL/RAJA pull request #1773
Opened 2024-11-25 22:53 UTC by artv3

# Summary

- This PR is a (refactoring, bugfix, feature, something else)
- It does the following (modify list as needed):
  - Modifies/refactors (class or method) (how?)
  - Fixes (issue number(s))
  - Adds (specific feature) at the request of (project or person)

# Design review (for API changes or additions---delete if unneeded)

On (date), we reviewed this PR.  We discussed the design ideas:

1. First idea or goal
2. Second idea
3. Third idea

This PR implements 1. and 3.  It leaves out 2. for the following reasons

- (impractical)
- (too big)
- (not a good idea anyway)

2024-12-20 17:33 UTC, artv3 commented
TODO: Compare the Caliper results with standard timers.

2024-12-27 16:23 UTC, artv3 commented
This isn't quite done, but I do want to trigger the CI to double check that we are passing test across the board.

2025-03-18 17:01 UTC, artv3 commented
ping: @daboehme @michaelmckinsey1 We have been adding integrating Caliper into RAJA via plugin mechanism, we were wondering if you might have some time to take a look at the PR?

2025-03-18 17:03 UTC, artv3 commented
@LLNL/raja-core , this will be an RAJA launch API breaking change. Launch will now use expt::KernelName instead of taking the const char * directly.

2025-03-20 19:00 UTC, daboehme commented
Hi @artv3, thanks for pushing this forward! Happy to have a Caliper plugin for RAJA.

The Caliper-specific code generally looks good to me. A few comments:

* We're unsure if the Caliper timer around the RAJA kernel launch measures the actual kernel execution or just the launch, especially if it's a async kernel on a GPU. In the latter case a user needs to enable `hip.gputime` or `cuda.gputime` in the Caliper config string to get the actual kernel execution time. This should at least be clarified in the documentation. There's also some concern that it would make it more difficult to compare times between CPU and GPU versions of a code if in one case we are measuring the whole kernel and in the other only the launch. If there is some way to have the Caliper region always include the whole kernel execution time (i.e. end the region after a stream synchronize) it might be better to use that.
* The `CALI_CXX_MARK_SCOPE` timers for the C versions in the two examples include the time in `std::cout`, which is probably not intended
* Not really Caliper-related but `getPlugin` seems a bit too generic of a name as a `extern "C"` function? Could probably use a prefix like `RAJA_getPlugin`

2025-03-21 22:07 UTC, artv3 commented on CMakeLists.txt
> +message(STATUS "Using Caliper from location =  ${caliper_DIR}")
TODO: remove message

2025-03-21 22:21 UTC, artv3 commented on include/RAJA/pattern/forall.hpp
> +struct get_kernel_name
since its an object give it a noun name, i.e. "KernelNameGetter"

2025-03-24 00:28 UTC, artv3 commented
> * getPlugin

Thanks @daboehme for the review! For remark 1. I agree it will come down to which kind of gpu synchronization policy the user will be using. We have async and sync gpu kernel launch policies, I will make clear about using using sync gpu policies or the `hip.gputime` or `cuda.gputime` options in cali-config. 

For remark 2, we were comparing to std timer options, we can probably remove those now. 

For remark 3, I'll bring that up with the team. We have been using that name in other plugins....

2025-03-24 07:56 UTC, artv3 commented
Hi @LLNL/raja-core team! Could I kindly get a review? I think we are good to go. Super excited to start using this in applications.

2025-03-24 15:01 UTC, MrBurmark commented on docs/sphinx/user_guide/profiling_with_caliper.rst
> +.. note:: The RAJA KernelName must be placed before the lambda to ensure proper behavior.
Probably something to discuss elsewhere, but is KernelName really necessary or could it just be Name to be more generic? There are places where multiple kernels may be called within a construct like kernel, scan, or sort.

2025-03-24 15:09 UTC, MrBurmark commented on include/RAJA/pattern/forall.hpp
> +      KernelNameHelper<decltype(kernel_name)>::getKernelName(kernel_name);
What is this doing?

2025-03-24 15:14 UTC, MrBurmark commented on include/RAJA/policy/cuda/params/kernel_name.hpp
>    nvtxRangePush(kn.name);
This seems like it could cause confusion as most people will probably not be aware of the consequences of mixing these options.

2025-03-24 15:37 UTC, MrBurmark commented on include/RAJA/util/PluginContext.hpp
> +  PluginContext(const Platform p, const std::string* name = nullptr)
Is this taking the name by pointer to make PluginContext copyable? Does it make more sense to take the string by reference, or string_view once we have it? We could use a static null string as the default.

2025-03-28 20:28 UTC, artv3 commented on docs/sphinx/user_guide/profiling_with_caliper.rst
> +.. note:: The RAJA KernelName must be placed before the lambda to ensure proper behavior.
@LLNL/raja-core any objections to changing "KernelName ->Name"?  This will break the API for forall.

2025-03-28 20:41 UTC, artv3 commented on docs/sphinx/user_guide/profiling_with_caliper.rst
> +.. note:: The RAJA KernelName must be placed before the lambda to ensure proper behavior.
I'll go with ``Name`` unless someone objects...

2025-03-28 21:35 UTC, artv3 commented on include/RAJA/policy/cuda/params/kernel_name.hpp
>    nvtxRangePush(kn.name);
@LLNL/raja-core , folks when caliper is not enabled should we still enable vendor specific ranges?

2025-03-28 23:06 UTC, artv3 commented on include/RAJA/pattern/forall.hpp
> +      KernelNameHelper<decltype(kernel_name)>::getKernelName(kernel_name);
resolved.

2025-03-28 23:19 UTC, artv3 commented on include/RAJA/pattern/params/forall.hpp
> +constexpr auto&& get_kernel_name(Args&&... args)
resolved

2025-03-31 18:09 UTC, artv3 commented on docs/sphinx/user_guide/profiling_with_caliper.rst
> +.. note:: The RAJA KernelName must be placed before the lambda to ensure proper behavior.
It is now name.... 👍

2025-03-31 19:26 UTC, artv3 commented on docs/sphinx/user_guide/profiling_with_caliper.rst
> +.. note:: The RAJA KernelName must be placed before the lambda to ensure proper behavior.
ah that is right, I'll move it out of expt as well.

2025-04-01 17:05 UTC, artv3 commented
@LLNL/raja-core can I get a review? I just did a pass at the docs, this PR should be complete.

2025-04-01 17:13 UTC, rchen20 commented on examples/plugin/caliper-plugin.cpp
> +// Copyright (c) 2016-24, Lawrence Livermore National Security, LLC
2016-25?

2025-04-01 17:18 UTC, rchen20 commented on include/RAJA/policy/hip/params/kernel_name.hpp
> -{
Do the other functions in here like `param_init`, `param_combine`, and `param_resolve` still need to remain in the `expt` namespace?

2025-04-01 18:25 UTC, artv3 commented on examples/plugin/caliper-plugin.cpp
> +// Copyright (c) 2016-24, Lawrence Livermore National Security, LLC
```suggestion
// Copyright (c) 2016-25, Lawrence Livermore National Security, LLC
```

2025-04-01 18:26 UTC, artv3 commented on examples/plugin/caliper-plugin.cpp
> +// Copyright (c) 2016-24, Lawrence Livermore National Security, LLC
```suggestion
// Copyright (c) 2016-25, Lawrence Livermore National Security, LLC
```

2025-04-01 18:36 UTC, artv3 commented on include/RAJA/policy/hip/params/kernel_name.hpp
> -{
I think `expt` is meant for more outward facing RAJA calls, I don't think keeping them in expt adds to anything.

2025-04-01 18:46 UTC, rhornung67 commented on docs/sphinx/user_guide/profiling_with_caliper.rst
> +In this section we demonstrate how to configure RAJA with Caliper, run a simple examples with kernel profiling,
```suggestion
In this section we demonstrate how to configure RAJA with Caliper, run simple examples with kernel profiling,
```

2025-04-01 18:47 UTC, rhornung67 commented on docs/sphinx/user_guide/profiling_with_caliper.rst
> +and a quick snapshot of hotspots of using the Thicket libary. The Thicket library is also developed at LLNL and freely available on GitHub,
```suggestion
and view a quick snapshot of hotspots of using the Thicket libary. The Thicket library is also developed at LLNL and freely available on GitHub,
```

2025-04-01 18:48 UTC, rhornung67 commented on docs/sphinx/user_guide/profiling_with_caliper.rst
> +This page is tailored to be a quickstart guide, for more detailed tutorials we refer the reader to the Caliper and Thicket tutorials.
Would it be useful to add links to those tutorials or note where they can be found (e.g., linked to Caliper and Thicket GitHub project pages)?

2025-04-01 18:52 UTC, rhornung67 commented on docs/sphinx/user_guide/profiling_with_caliper.rst
> +Caliper serves as a portable profiling library which may be configured with various vendor options. For the most up to date
Please add a blank line before section header and text.

2025-04-01 18:52 UTC, rhornung67 commented on docs/sphinx/user_guide/profiling_with_caliper.rst
> +Caliper annotations of RAJA kernels work through the RAJA kernel naming mechanism which is currently only supported in forall
Please add a blank line before section header and text.

2025-04-01 18:53 UTC, rhornung67 commented on docs/sphinx/user_guide/profiling_with_caliper.rst
> +and launch. The ``RAJA::Name`` container holds a string and used for profiling in Caliper. Kernels
```suggestion
and launch. The ``RAJA::Name`` container holds a string and is used for profiling in Caliper. Kernels
```

2025-04-01 18:55 UTC, rhornung67 commented on docs/sphinx/user_guide/profiling_with_caliper.rst
> +which are not provided a name are ommited from Caliper profiling::
I think this sentence should come after the following code example which shows a kernel with a name.

2025-04-01 18:57 UTC, rhornung67 commented on docs/sphinx/user_guide/profiling_with_caliper.rst
> +         When Caliper is configured with RAJA all performance profiling is performed by Caliper.
Is this last sentence also supposed to be a note? If so, it is missing the note annotation. If not, it should be separated from the previous note by a blank line and not indented.

2025-04-01 18:57 UTC, rhornung67 commented on docs/sphinx/user_guide/profiling_with_caliper.rst
> +Once Caliper is configured with RAJA and kernels are provided with a kernel name, the Caliper library provides various
Please add a blank line before section header and text.

2025-04-01 18:59 UTC, rhornung67 commented on docs/sphinx/user_guide/profiling_with_caliper.rst
> +Once Caliper is configured with RAJA and kernels are provided with a kernel name, the Caliper library provides various
```suggestion
Once RAJA is configured with Caliper and kernels are provided with kernel names, the Caliper library provides various
```

Also, please add a blank line before section header and text.

2025-04-01 18:59 UTC, rhornung67 commented on docs/sphinx/user_guide/profiling_with_caliper.rst
> +Configuring a ROCM trace file with Caliper may be done using the following command::
Please add a blank line before section header and text.

2025-04-01 19:01 UTC, rhornung67 commented on docs/sphinx/user_guide/profiling_with_caliper.rst
> +Using python jupyter notebooks and the Hatchet library we can load the .cali file and begin analysing
```suggestion
Using python jupyter notebooks and the Hatchet library we can load the .cali file and begin analyzing
```

2025-04-01 19:01 UTC, rhornung67 commented on docs/sphinx/user_guide/profiling_with_caliper.rst
> +The capabilities of Caliper and Hatchet exceed what has been presented here. Our main goal was to provide
Please add a blank line before section header and text.

2025-04-01 19:08 UTC, rhornung67 commented on include/RAJA/pattern/params/kernel_name.hpp
> +struct Name : public ::RAJA::expt::detail::ForallParamBase
Why is `ForallParamBase` in `expt` namespace? It seems `detail` would be sufficient.

2025-04-01 19:08 UTC, rhornung67 commented on include/RAJA/pattern/params/kernel_name.hpp
> +  Name(const char* name_in) : name(name_in) {}
Please mark single arg ctors `explicit` to prevent unintended implicit type conversions.

2025-04-01 19:10 UTC, rhornung67 requested changes
A few questions, plus documentation requests.

2025-04-01 20:17 UTC, rchen20 commented on include/RAJA/policy/hip/params/kernel_name.hpp
> -{
@artv3 I made changes to these `kernel_name.hpp`s which leave the `expt` namespace in there, and scope `Name` more precisely. Please take a look when you can.

2025-04-01 22:05 UTC, artv3 commented on docs/sphinx/user_guide/profiling_with_caliper.rst
> +This page is tailored to be a quickstart guide, for more detailed tutorials we refer the reader to the Caliper and Thicket tutorials.
Those all clickable links that will take the user directly to their page.

2025-04-01 22:07 UTC, artv3 commented on benchmark/ltimes.cpp
> +    RAJA::launch<pol_launch>(RAJA::ExecPlace::HOST, RAJA::LaunchParams(), [=] RAJA_HOST_DEVICE (RAJA::LaunchContext ctx){
The loop methods below are host device, CUDA will emit warnings about having a host device function inside a strictly host function.

2025-04-01 22:08 UTC, artv3 commented
Everything should now be addressed, thanks team!

2025-04-01 22:39 UTC, rhornung67 commented on docs/sphinx/user_guide/profiling_with_caliper.rst
> +This page is tailored to be a quickstart guide, for more detailed tutorials we refer the reader to the Caliper and Thicket tutorials.
What I meant was change "we refer the reader to the Caliper and Thicket tutorials" to "we refer the reader to the Caliper and Thicket tutorials, which are accessible on the GitHub pages for those projects"

2025-04-01 22:40 UTC, rhornung67 approved these changes
One minor comment, which you can choose to ignore.

2025-04-01 22:46 UTC, rchen20 approved these changes

2025-04-02 16:00 UTC, MrBurmark commented on include/RAJA/pattern/forall.hpp
> +
```suggestion
```

2025-04-02 16:02 UTC, MrBurmark commented on include/RAJA/pattern/launch/launch_core.hpp
> +  launch_t::exec(Res::get_default(), launch_params, nullptr, p_body, reducers);
Should the kernel_name argument be removed instead of just passing nullptr now?

2025-04-02 16:07 UTC, MrBurmark commented on test/include/RAJA_test-plugin-kernelpol.hp
Why is this empty file here?

2025-04-02 16:07 UTC, MrBurmark commented on test/integration/plugin_for_test_dynamic.cp
Why is this empty file here?

2025-04-02 16:25 UTC, MrBurmark commented on src/RuntimePluginLoader.cpp
> +      (RuntimePluginLoader::Parent * (*)()) dlsym(plugin, "RAJAGetPlugin");
This seems like an ABI breaking change. Do we plan to have any patch releases before the next major release? @davidbeckingsale @rhornung67

2025-04-02 16:43 UTC, artv3 commented on src/RuntimePluginLoader.cpp
> +      (RuntimePluginLoader::Parent * (*)()) dlsym(plugin, "RAJAGetPlugin");
suggestion was from @daboehme

2025-04-02 17:57 UTC, MrBurmark commented on src/RuntimePluginLoader.cpp
> +      (RuntimePluginLoader::Parent * (*)()) dlsym(plugin, "RAJAGetPlugin");
Maybe we can deprecate "getPlugin" but still look for it. Then remove it int eh next release.

2025-04-02 23:31 UTC, MrBurmark commented on src/RuntimePluginLoader.cpp
> +      (RuntimePluginLoader::Parent * (*)()) dlsym(plugin, "RAJAGetPlugin");
I have added the extra check for the old name just in case for now.

2025-04-03 15:40 UTC, artv3 commented on src/RuntimePluginLoader.cpp
> +      (RuntimePluginLoader::Parent * (*)()) dlsym(plugin, "RAJAGetPlugin");
@MrBurmark , I tried building with the latest change and I hit the following build error: 
```
RAJA/src/RuntimePluginLoader.cpp(120): error #20: identifier "error" is undefined
```

2025-04-03 16:35 UTC, MrBurmark commented on src/RuntimePluginLoader.cpp
> +      (RuntimePluginLoader::Parent * (*)()) dlsym(plugin, "RAJAGetPlugin");
That's what I get for making changes in the web interface.

2025-04-03 18:08 UTC, MrBurmark commented on src/RuntimePluginLoader.cpp
> +      (RuntimePluginLoader::Parent * (*)()) dlsym(plugin, "RAJAGetPlugin");
I assumed that we have a CI test that would find that, is that not the case?

2025-04-04 12:46 UTC, artv3 commented on include/RAJA/pattern/launch/launch_core.hpp
> +  launch_t::exec(Res::get_default(), launch_params, nullptr, p_body, reducers);
sure, good call.

2025-04-04 13:23 UTC, artv3 commented
@LLNL/raja-core , I think we should be good to go now -- I also turned on `RAJA_ENABLE_PLUGINS` within our docker clang15 build. Would someone be able to weigh in if that would have caught @MrBurmark's expected build test failure? 

Any objections to merging if this comes out green?

2025-04-04 18:21 UTC, MrBurmark approved these changes

2025-04-04 18:22 UTC, MrBurmark commented
I explicitly added a "getPlugin" test. I went ahead and approved the PR.

2025-04-04 19:52 UTC, merged

2025-04-04 19:53 UTC, artv3 commented
> I explicitly added a "getPlugin" test and manually confirmed that it fails if the "getPlugin" loading code is not there. I went ahead and approved the PR.

Awesome! Thanks!