Move generic documentation to shared location
LLNL/RAJA pull request #905
Opened 2020-10-03 01:51 UTC by adrienbernede

This PR moves and complete documentation to a shared location (versioned in https://github.com/LLNL/radiuss-ci).

The parts of the documentation concerned are the usage of Uberenv and Gitlab CI.

Relates to https://github.com/LLNL/Umpire/pull/442

2020-10-07 20:50 UTC, adrienbernede commented
LGTM

2020-10-26 18:34 UTC, adrienbernede commented
@davidbeckingsale It seems to me the changes here are harmless enough to be merged ;)

2021-01-29 02:10 UTC, adrienbernede commented
@davidbeckingsale will it merged this time? ;)

2021-02-08 16:15 UTC, adrienbernede commented
@rhornung67 I would appreciate some feedback here: similar changes were merged in Umpire and CHAI.
Anything left to do to get it ready for RAJA too?

2021-02-08 16:40 UTC, rhornung67 commented on docs/sphinx/dev_guide/host_config.rst
> +.. host_config:
Please don't remove the copyright statement from files.

Also, please add it to the other files you added.

2021-02-08 16:44 UTC, rhornung67 requested changes
Looks OK to me, except for my comments on the copyright statements.  Also, branch needs to be updated with base branch.

2021-02-08 16:57 UTC, adrienbernede commented
@rhornung67 Done. Thank you!

2021-02-08 16:58 UTC, rhornung67 approved these changes

2021-02-08 18:19 UTC, adrienbernede commented
@rhornung67 Should I motivate another reviewer or is it OK like this (I don't have merge powers)?

2021-02-08 18:32 UTC, rhornung67 commented
@davidbeckingsale when you have a minute, please look this over. If you're OK with it, we'll merge i t.

2021-02-08 19:08 UTC, davidbeckingsale commented
Why does this have a BLT change?

2021-02-08 19:09 UTC, rhornung67 commented
> Why does this have a BLT change?

I was wondering that too. That's why I wanted you to look at this.

2021-02-08 19:10 UTC, adrienbernede commented
Hmm, maybe a mix-up during the merge conflict resolution... I’ll have a look.

2021-02-08 19:18 UTC, adrienbernede commented
@rhornung67 @davidbeckingsale Sorry for overlooking this... That was indeed a mistake after a merge.

2021-02-08 19:39 UTC, davidbeckingsale approved these changes

2021-02-08 19:40 UTC, rhornung67 approved these changes

2021-02-11 15:18 UTC, merged