Improve readme
LLNL/RAJA pull request #937
Opened 2020-12-29 23:18 UTC by rhornung67

# Summary

- This PR updates and improves the README file.

2020-12-30 17:02 UTC, rchen20 approved these changes

2020-12-30 23:16 UTC, trws commented on README.md
>  Lawrence Livermore National Laboratory (LLNL), that enable architecture
```suggestion
Lawrence Livermore National Laboratory (LLNL), that enables architecture
```

2020-12-30 23:17 UTC, trws commented on README.md
> +RAJA targets portable, parallel loop execution by providing building blocks
```suggestion
RAJA offers portable, parallel loop execution by providing building blocks 
```

2020-12-30 23:18 UTC, trws commented on README.md
> +RAJA is rooted in a perspective based on decades of experience working on
```suggestion
RAJA's design is rooted in decades of experience working on 
```

2020-12-30 23:20 UTC, trws reviewed
Looks really good to me.  I popped a few comments in with suggestions for some little grammar or wording preference things, but this looks like a nice rework.

2021-01-04 16:36 UTC, rhornung67 commented on README.md
>  Lawrence Livermore National Laboratory (LLNL), that enable architecture
Done.

2021-01-04 16:36 UTC, rhornung67 commented on README.md
> +RAJA targets portable, parallel loop execution by providing building blocks
Done.

2021-01-04 16:37 UTC, rhornung67 commented on README.md
> +RAJA is rooted in a perspective based on decades of experience working on
Done.

2021-01-04 16:38 UTC, rhornung67 commented
All reviewer comments have been addressed.

2021-01-04 16:44 UTC, mdavis36 requested changes

2021-01-04 16:44 UTC, mdavis36 commented on README.md
> +RAJA's desing is rooted in decades of experience working on
design

2021-01-04 16:44 UTC, mdavis36 commented on README.md
> +and which are fundamental to applications we work with.
remove either 'and' or 'which' here

2021-01-04 16:47 UTC, rhornung67 commented on README.md
> +RAJA's desing is rooted in decades of experience working on
Fixed. Thanks.

2021-01-04 16:48 UTC, rhornung67 commented on README.md
> +and which are fundamental to applications we work with.
Done.

2021-01-04 16:49 UTC, mdavis36 approved these changes
Looks good :+1:

2021-01-04 16:54 UTC, MrBurmark approved these changes

2021-01-04 16:54 UTC, trws approved these changes
LGTM.

2021-01-04 20:10 UTC, artv3 approved these changes

2021-01-04 20:11 UTC, merged